### ISSUE TITLE
Rust 英文文章推荐

### ISSUE THREAD

**Issue by suhanyujie** [rustlang-cn/nutrition#10]
### 英文文章推荐
- 文章地址 https://medium.com/swlh/understanding-closures-in-rust-21f286ed1759
- 简介：关于 Rust 闭包的介绍
- tips：缺少文章推荐模板啊，哈哈

**Comment by krircc** [comment]
我其实也有好几篇文章，大家缺少参与热情呀。。

**Comment by amerysong** [comment]
https://boats.gitlab.io/blog/，rust大神的博客，很多都很有用，没事可以翻译一下，

**Comment by yangwenmai** [comment]
> [https://boats.gitlab.io/blog/，rust 大神的博客，很多都很有用，没事可以翻译一下，](https://boats.gitlab.io/blog/%EF%BC%8Crust%E5%A4%A7%E7%A5%9E%E7%9A%84%E5%8D%9A%E5%AE%A2%EF%BC%8C%E5%BE%88%E5%A4%9A%E9%83%BD%E5%BE%88%E6%9C%89%E7%94%A8%EF%BC%8C%E6%B2%A1%E4%BA%8B%E5%8F%AF%E4%BB%A5%E7%BF%BB%E8%AF%91%E4%B8%80%E4%B8%8B%EF%BC%8C)

https://boats.gitlab.io/blog/post/zero-cost-abstractions/
这篇文章有翻译吗？

**Comment by amerysong** [comment]
@yangwenmai 已列入翻译计划

**Comment by krircc** [comment]
@amerysong [Rust Web开发实战-前端](https://rustlang-cn.org/read/07/practical-rust-web-development-front-end.html)已发布

**Comment by krircc** [comment]
@suhanyujie  [文章推荐模板](https://github.com/rustlang-cn/nutrition/issues/1#issuecomment-511288423)哈哈

**Comment by krircc** [comment]
@suhanyujie  已收录 [理解Rust中的闭包](https://github.com/rustlang-cn/nutrition/issues/14)
