### ISSUE TITLE
2019-6-英文翻译-1：Threads in rust

### ISSUE THREAD

**Issue by krircc** [rustlang-cn/nutrition#2]
### Threads in rust

- 原文链接：https://chilimatic.hashnode.dev/threads-in-rust-cjwmbxw9e003pzjs19n7pa0bt
- 翻译文件：https://github.com/rustlang-cn/nutrition/blob/master/TODO/2019-06-2/1-threads-in-rust.md
- 简要介绍：该文全面介绍操作系统CPU，内存，进程，线程，协程到Rust线程，API使用，特点分类值得阅读分享

### 完成并勾选：

* [x] 本文很值得翻译，我推荐
* [x] 已经过初步搜索，暂未发现中文版译文

### 当前状态：校对中

校对文件 ：https://github.com/rustlang-cn/nutrition/blob/master/TODO/2019-06-2/1-threads-in-rust.md

**Comment by suhanyujie** [comment]
@krircc   这个文章在“掘金翻译计划”中即将被翻译，感觉不用重复翻译 。
https://github.com/xitu/gold-miner/issues/5999

**Comment by krircc** [comment]
@suhanyujie 掘金准许转载不？好像要很多人同意，除非翻译者自己向我们投稿吧

**Comment by suhanyujie** [comment]
对 最好是译者投稿。不过，我觉得转载应该可以，因为内容中都注明了作者 译者 校对者等信息。

**Comment by krircc** [comment]
@rustlang-cn/rustlang-cn 初步翻译，欢迎试读和校对

**Comment by suhanyujie** [comment]
@krircc  文章开始部分的 “原文链接” 貌似是错误的，链接到的是 rust-streams 文章

**Comment by krircc** [comment]
@suhanyujie 对对，多谢指正

**Comment by krircc** [comment]
已经发布
