### ISSUE TITLE
关于文本规范

### ISSUE THREAD

**Issue by suhanyujie** [rustlang-cn/nutrition#6]
建议采用跟[这里](https://github.com/xitu/gold-miner/wiki/%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E8%A7%84%E5%88%99%E6%8C%87%E5%8C%97)类似的文本规范，便于校对。

**Comment by krircc** [comment]
@shanPic 首先感谢你的建议，已添加到[README](https://github.com/rustlang-cn/nutrition/blob/master/README.md#%E8%8B%B1%E6%96%87%E7%BF%BB%E8%AF%91).

目前在营养计划实行初始阶段，不能太严格，打击大家参与积极性，所以作为非强制要求.
